server:
  port: 8888

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: file://${HOME}/workspace/config-server-repository
#          uri: https://github.com/spring-cloud-samples/config-repo
    fail-fast: true

logging:
  level:
    ROOT: INFO
    org.spring.framework.cloud.config: DEBUG
