server:
  port: 8888

spring:
  cloud:
    config:
      server:
        native:
          searchLocations: file://${user.home}/workspace/event-driven-microservices/config-server-repository
  profiles:
    active: native

logging:
  level:
    ROOT: INFO
    org.spring.framework.cloud.config: DEBUG